# Generated by Django 5.0.14 on 2025-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DealMover', '0002_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=255)),
                ('Company_Name', models.TextField()),
                ('Transaction_Type', models.TextField()),
                ('Products_Services', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
