# Generated by Django 5.0.14 on 2025-05-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DealMover', '0004_mymodel_uploadedfile_delete_dealvault'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('deal_stage', models.CharField(max_length=255)),
                ('projected_close_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dealmover_projects',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
